version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - '9000:9000' # Acceso a la interfaz web de Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Permite que Portainer administre Docker
      - portainer_data:/data # Persistencia de datos de Portainer
    restart: always

volumes:
  portainer_data:
    driver: local
