apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-digitus-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /mnt/data/db-digitus
