apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig-configmap
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        server: https://<API_SERVER_URL>
        certificate-authority-data: <CERTIFICATE_DATA>
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: kube-admin
      name: kube-admin-context
    current-context: kube-admin-context
    kind: Config
    preferences: {}
    users:
    - name: kube-admin
      user:
        client-certificate-data: <CLIENT_CERTIFICATE_DATA>
        client-key-data: <CLIENT_KEY_DATA>
