apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
        - name: portainer
          image: portainer/portainer-ce:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /data
              name: portainer-data
          env:
            - name: ADMIN_USER
              value: "admin"
            - name: ADMIN_PASSWORD
              value: "admin1234567"
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: portainer-data
          persistentVolumeClaim:
            claimName: portainer-pvc
