apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: traefik:v2.5
          command:
            - '--api.insecure=true'
            - '--providers.kubernetescrd=true'
            - '--entrypoints.web.address=:80'
          ports:
            - containerPort: 80
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  selector:
    app: traefik
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: api
      port: 8080
      targetPort: 8080
  type: LoadBalancer

