apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-user
  template:
    metadata:
      labels:
        app: service-user
    spec:
      containers:
        - name: service-user
          image: blandskron/service-user:v1.0
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-digitus:5432/db_digitus
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: D1g1tus_.2024
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: service-user
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: service-user
